---
title: "Bilderrating_Drift_Report.docx"
output: word_document
---
##Rating Drifts across all Subjects

#Affective Rating Drifts
```{r  fig.width=6, results='asis', fig.height=5, warning=FALSE, eval=TRUE, message=FALSE, tidy=TRUE, dev='png', echo=FALSE, fig.show='hold',}
library(ggplot2)
setwd('C:\\Users\\Milan.an\\Google Drive\\VPPG_Exchange\\Experimente\\PDT\\analysis\\scripts\\R\\plot_bilderratings\\')
load('data_pdt.Rdat')

##All subjects - Affective Ratings, facets for arousal, dominance and valence  

ord.aro=lm(arousal ~ order, data_pdt_aff)
ord.dom=lm(dominance ~ order, data_pdt_aff)
ord.val=lm(valence ~ order, data_pdt_aff)

require(memisc)

AffRatTab <- mtable('arousal' = ord.aro,
                    'dominance' = ord.dom,
                    'valence' = ord.val,
                    summary.stats = c('R-squared','p','F','N'))

require(pander)


##All subjects - Affective Ratings, facets for arousal, dominance and valence  

  aPlot=ggplot(data_pdt_aff_long, aes(x=order, y=affRat));
  aPlot=aPlot + facet_wrap(~affCat, ncol=3)
  aPlot=aPlot+layer(geom="point")+ geom_point(size=1, alpha=1/2) + xlab('Trial') + ylab('Affective Rating') + ggtitle(paste('All Subjects - Affective Ratings'));
  aPlot=aPlot+ theme(plot.title = element_text(size = rel(1.5)));
  aPlot=aPlot+geom_smooth(method=lm, se=FALSE, size=1.3, color='red');
  
  plot(aPlot);
#Quantifying the effects of order with regression coefficients:
pander(AffRatTab)
#pander(AffRatTab);

```

#Affective Sensitivity Drifts

```{r  fig.width=6, results='asis', fig.height=5, warning=FALSE, eval=TRUE, message=FALSE, tidy=TRUE, dev='png', echo=FALSE, fig.show='hold',}
library(ggplot2)
setwd('C:\\Users\\Milan.an\\Google Drive\\VPPG_Exchange\\Experimente\\PDT\\analysis\\scripts\\R\\plot_bilderratings\\')
load('data_pdt.Rdat')

##All subjects - Affective Ratings, facets for arousal, dominance and valence  

ord.aroAbs=lm(abs(data_pdt_aff$arousal) ~ data_pdt_aff$order)
ord.domAbs=lm(abs(data_pdt_aff$dominance) ~ data_pdt_aff$order)
ord.valAbs=lm(abs(data_pdt_aff$valence) ~ data_pdt_aff$order)


require(memisc)
AffSenTab <- mtable('absArousal' =ord.aroAbs,
                    'absDominance' = ord.domAbs,
                    'absValence' = ord.valAbs,
                    summary.stats = c('R-squared','p','F','N'))
require(pander)


##All subjects - Affective Sensitivity, facets for arousal, dominance and valence
  aPlot=ggplot(data_pdt_aff_long, aes(x=order, y=Sensitivity));
  aPlot=aPlot + facet_wrap(~affCat, ncol=3)
  aPlot=aPlot+layer(geom="point")+ geom_point(size=1, alpha=1/2) + xlab('Trial') + ylab('Affective Sensitivity') + ggtitle(paste('All Subjects - Affective Sensitivity (rev. Indifference)'));
  aPlot=aPlot+ theme(plot.title = element_text(size = rel(1.5)));
  aPlot=aPlot+geom_smooth(method=lm, se=FALSE, size=1.3, color='red');

  plot(aPlot);
#Quantifying the effects of order with regression coefficients:
  pander(AffSenTab);


```


##Rating Drifts for each Subject Separately

Output of the lmList regression which fits a line for each suject separately.
```{r  fig.width=15, results='asis', fig.height=5, warning=FALSE, eval=TRUE, message=FALSE, tidy=TRUE, dev='png', echo=FALSE, fig.show='hold',}
library(ggplot2)
setwd('C:\\Users\\Milan.an\\Google Drive\\VPPG_Exchange\\Experimente\\PDT\\analysis\\scripts\\R\\plot_bilderratings\\')
load('data_pdt.Rdat')
require(pander)
require(lme4)

#Get regression coefficients for each separate subject

data_pdt_affOrd <- subset(data_pdt_aff, select =c(subject,order, arousal, dominance, valence)); #subseting because lmList has a problem with a full set
data_pdt_affOrd = data_pdt_affOrd[order(as.vector(data_pdt_affOrd$subject)),];

ord.aro_subj=lmList(arousal~order | subject, data_pdt_affOrd);
#summary(ord.aro_subj);

data_pdt_affOrd1 <- subset(data_pdt_affOrd, subject=='PhysioVP0002');

ord.aro_subj1=lm(arousal~order, data_pdt_affOrd1);
#summary(ord.aro_subj1);



ord.aro_subj=lmList(arousal~order | subject, data_pdt_affOrd);
ord.val_subj=lmList(valence~order | subject, data_pdt_affOrd);
ord.dom_subj=lmList(dominance~order | subject, data_pdt_affOrd);



RegDat <- function(lm) {
  out=data.frame(summary(lm)$coefficients[,,2]);
  names(out)=c('beta',	'SE', 't','Pr.t');
  out$F= summary(lm)$fstatistic[,1];
  out$R.sq=summary(lm)$r.squared;
return(out)};

ord.aro_subj_dat=RegDat(ord.aro_subj);
#hist(ord.aro_subj_dat$beta)
ord.aro_subj_tBeta=t.test(ord.aro_subj_dat$beta);

ord.dom_subj_dat=RegDat(ord.dom_subj);
#hist(ord.dom_subj_dat$beta);
ord.dom_subj_tBeta=t.test(ord.dom_subj_dat$beta);

ord.val_subj_dat=RegDat(ord.val_subj);
#hist(ord.val_subj_dat$beta);
ord.val_subj_tBeta=t.test(ord.val_subj_dat$beta);

panderOptions('round', 5)
panderOptions('keep.trailing.zeros', TRUE)
cat("  \n  \n## lmList regression statistics: Arousal~Order \n ")
pandoc.table(ord.aro_subj_dat, style = "simple", split.table = Inf)
cat("  \n  \n## lmList regression statistics: Arousal~Dominance \n ")
pandoc.table(ord.dom_subj_dat, style = "simple", split.table = Inf)
cat("  \n  \n## lmList regression statistics: Arousal~Valence \n ")
pandoc.table(ord.val_subj_dat, style = "simple", split.table = Inf)


cat("  \n  \n### T-test Arousal~Order  \n ")
cat("Testing whether the mean of beta estimates of the model Arousal~Order across participants has a value of zero (null hypothesis).  \n")
pander(ord.aro_subj_tBeta)
cat("  \n  \n### T-test Dominance~Order  \n")
cat("Testing whether the mean of beta estimates of the model Dominance~Order across participants has a value of zero (null hypothesis).  \n")
pander(ord.dom_subj_tBeta)
cat("  \n  \n### T-test Valence~Order  \n")
cat("Testing whether the mean of beta estimates of the model Valence~Order across participants has a value of zero (null hypothesis).  \n")
pander(ord.val_subj_tBeta)

#showing the lmList parameteres distributions

ord.aff_subj_dat=rbind(cbind(ord.aro_subj_dat, origin="Order~Arousal"),
      cbind(ord.dom_subj_dat, origin="Order~Dominance"),
      cbind(ord.val_subj_dat, origin="Order~Valence"));

bPlot = ggplot(data=ord.aff_subj_dat, aes(beta)) + ggtitle(paste('lmList regression statistics: distribution of beta parameters'));
bPlot = bPlot + facet_wrap(~origin, ncol=3)
bPlot = bPlot+ geom_histogram(breaks=seq(-0.005,0.005, by =0.0005), col="red", fill="black", alpha = .6)
plot(bPlot)

pPlot = ggplot(data=ord.aff_subj_dat, aes(Pr.t)) + ggtitle(paste('lmList regression statistics: distribution of p values'));
pPlot = pPlot + facet_wrap(~origin, ncol=3)
pPlot = pPlot+ geom_histogram(breaks=seq(0,0.4, by =0.05),col="black", fill="red", alpha = .3)
pPlot = pPlot+ geom_histogram(breaks=seq(0,0.4, by =0.01),col="red", fill="black", alpha = .6)
plot(pPlot)

#data_pdt_aff_long$subjectNum=
##Each Subject - Arousal, facets for subject
  aPlot=ggplot(data_pdt_aff_long, aes(x=order, y=affRat));
  aPlot=aPlot + facet_grid(affCat~subject)
  aPlot=aPlot+layer(geom="point")+ geom_point(size=1, alpha=1/2) + xlab('Trial') + ylab('Affective Rating') + ggtitle(paste('Affective ratings drift - regression line for each subject'))
  aPlot=aPlot+ theme(plot.title = element_text(size = rel(1.5)));
  aPlot=aPlot+geom_smooth(method='lm', se=FALSE, size=1.3, color='red');
plot(aPlot)


```

